// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxdivxsfggilewgmvryh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZGl2eHNmZ2dpbGV3Z212cnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODI3ODIsImV4cCI6MjA2ODY1ODc4Mn0.nCTmaCpEMPNag-fh5Yf4zzPOpb6l4QnhT4rTDsla3wA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});